// Import Components

// Import Custom Hooks
import Button from 'components/Button'
import { Github } from 'components/icons/Github'
import Layout from 'containers/Layout'
import { useUserCtx } from 'hooks/useUserCtx'

import Head from 'next/head'
import Image from 'next/image'
// Import Styles
import styles from 'styles/index.module.scss'

export default function Home() {
  const { user, session } = useUserCtx()

  console.log(user)
  console.log(session)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className={styles.section}>
          <h1>Devtter</h1>
          <h2>
            Talk about develpment <br /> with developers 👨‍💻💻🖥👩‍💻
          </h2>
          <div>
            {session === null && (
              <Button onClick={() => alert('GithubLogin')}>
                <Github fill="#fdfdfd" width={24} height={24} />
                Login with Github
              </Button>
            )}
            {session === true && (
              <div>
                <img src={user.avatar_url} />
                <strong>{user.user_name}</strong>
              </div>
            )}
          </div>
        </section>
      </Layout>
    </>
  )
}
