import Image from 'next/image'
import Head from 'next/head'
import { useRouter } from 'next/router'
// Import Components
import { Github } from 'components/icons/Github'
import Avatar from 'components/Avatar'
import Button from 'components/Button'
import Layout from 'containers/Layout'

// Import Custom Hooks
import { useUserCtx } from 'hooks/useUserCtx'

// Import Styles
import styles from 'styles/index.module.scss'
import { useEffect } from 'react'
import Loader from 'components/Loader'
import { supabase } from 'supabase/client'
import { loginWithGithub } from 'supabase/utils'
import LogoutBtn from 'components/LogoutBtn'

export default function Home() {
  const router = useRouter()
  const { user, loginWithGithub } = useUserCtx()

  const halndleLogin = async () => {
    const user = await loginWithGithub()
  }

  // console.log(user)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className={styles.section}>
          <h1>Devtter</h1>
          <h2>
            Talk about develpment <br /> with developers 👨‍💻💻🖥👩‍💻
          </h2>
          <div>
            {user === null && (
              <Button onClick={halndleLogin}>
                <Github fill="#fdfdfd" width={24} height={24} />
                Login with Github
              </Button>
            )}
            {user && user.avatar_url && (
              <div>
                <Avatar
                  src={user.avatar_url}
                  alt={user.user_name}
                  text={user.user_name}
                  withText
                />
                <LogoutBtn />
              </div>
            )}

            {user === undefined && <Loader />}
          </div>
        </section>
      </Layout>
    </>
  )
}
